# Generated by Django 5.1 on 2024-09-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdataset',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='otp_created_at',
        ),
    ]
