# Generated by Django 5.1 on 2024-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_remove_userdataset_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userdataset',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
