# Generated by Django 5.1 on 2024-09-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='timing',
        ),
    ]
