# Generated by Django 5.1 on 2024-09-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_menu_rating_remove_menu_timing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingOrder',
            new_name='FinalOrder',
        ),
    ]
