# Generated by Django 5.1 on 2024-09-24 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_cart_quantity_finalorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
