# Generated by Django 5.1 on 2024-09-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_finalorder_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='ordered',
            new_name='complete',
        ),
    ]
