# Generated by Django 5.1 on 2024-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_rename_ordered_finalorder_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='order_details',
            new_name='cart_details',
        ),
    ]
