# Generated by Django 5.1 on 2024-09-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_burger_gujarati_panjabi_southindian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burger',
            new_name='Dessert',
        ),
    ]
