# Generated by Django 5.1 on 2024-09-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_rename_burger_dessert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='PizzaBurger',
        ),
    ]
